In [1]:
import pandas as pd

In [5]:
df = pd.read_csv("kindergardens_.csv", dtype={"location": "string"})

In [6]:
df.head()

,id,fullname,shortname,number,category,vid_uchrezhdeniya,organiz_pravov_forma,podchinenie,address,telephone,email,location
0,1,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1439,1 439,Дошкольное образовательное учреждение,Детский сад компенсирующего вида,Бюджетное,Северо-Восточное окружное управление образования,"""127273 г. Москва, ул. Отрадная, д. 5 ""Б""",(499) 907-63-66,detsad1439@mail.ru,POINT (37.6076187 55.8591187)
1,2,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 938,938,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Северо-Восточное окружное управление образования,"127349, город Москва, улица Лескова, дом 6 Г",(499) 909-00-44,detskiysad938@yandex.ru,POINT (37.5925685 55.8970746)
2,3,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1243,1 243,Дошкольное образовательное учреждение,Детский сад компенсирующего вида,Бюджетное,Юго-Западное окружное управление образования,"119333, г. Москва, ул. Фотиевой, дом 8",8(499)137-35-75,dou1243@ou.mosuzedu.ru; tngulakova@bk.ru,POINT (37.5623493 55.70100369999999)
3,4,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1432,1 432,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Юго-Западное окружное управление образования,"119331, г.Москва, улица Марии Ульяновой, дом ...",8(499)138-38-47,dou1432@ou.mosuzedu.ru,POINT (37.5203819 55.680765)
4,5,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 824,824,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Западное окружное управление образования,"121615, г.Москва, ул. Ельнинская, д. 16",(499) 141-75-87,dou824@bk.ru,POINT (37.4240156 55.7386473)

In [7]:
df["location"] = (
    df["location"]
    .str.strip()
    .str.replace(
        r"^POINT\s*\(\s*([-\d.]+)\s+([-\d.]+)\s*\)$",
        r"POINT(\1 \2)",
        regex=True
    )
    .astype("string")
)

In [8]:
df.head()

,id,fullname,shortname,number,category,vid_uchrezhdeniya,organiz_pravov_forma,podchinenie,address,telephone,email,location
0,1,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1439,1 439,Дошкольное образовательное учреждение,Детский сад компенсирующего вида,Бюджетное,Северо-Восточное окружное управление образования,"""127273 г. Москва, ул. Отрадная, д. 5 ""Б""",(499) 907-63-66,detsad1439@mail.ru,POINT(37.6076187 55.8591187)
1,2,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 938,938,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Северо-Восточное окружное управление образования,"127349, город Москва, улица Лескова, дом 6 Г",(499) 909-00-44,detskiysad938@yandex.ru,POINT(37.5925685 55.8970746)
2,3,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1243,1 243,Дошкольное образовательное учреждение,Детский сад компенсирующего вида,Бюджетное,Юго-Западное окружное управление образования,"119333, г. Москва, ул. Фотиевой, дом 8",8(499)137-35-75,dou1243@ou.mosuzedu.ru; tngulakova@bk.ru,POINT(37.5623493 55.70100369999999)
3,4,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1432,1 432,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Юго-Западное окружное управление образования,"119331, г.Москва, улица Марии Ульяновой, дом ...",8(499)138-38-47,dou1432@ou.mosuzedu.ru,POINT(37.5203819 55.680765)
4,5,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 824,824,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Западное окружное управление образования,"121615, г.Москва, ул. Ельнинская, д. 16",(499) 141-75-87,dou824@bk.ru,POINT(37.4240156 55.7386473)

In [9]:
df.to_csv("kindergardens_points.csv", index=False)