In [1]:
import pandas as pd

In [26]:
df = pd.read_csv("policlinics_2.csv")
df.head(10)

,Category,FullName,ShortName,address,location
0,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 48 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.74188144 55.694081483)
1,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 110 филиал № 3 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.579720035 55.814071213)
2,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 131 филиал № 2 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.514133891 55.712573334)
3,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 91 филиал № 2 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.617093435 55.714439742)
4,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 150 филиал № 3 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.74702014 55.651710188)
5,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 61 филиал № 2 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.66475943 55.729622049)
6,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 122 филиал № 2 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.802977987 55.816576302)
7,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 125 филиал № 2 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.577723351 55.901862208)
8,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 150 филиал № 2 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.769740489 55.670141578)
9,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 48 филиал № 2 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.776995007 55.701673799)

In [3]:
df = pd.read_csv("policlinics_1_2.csv", sep=";")



# Удаление одного столбца
# df = df.drop(columns=['ticket_id'])

# Удаление нескольких столбцов сразу
# df = df.drop(columns=['столбец_1', 'столбец_2'])
df.head(3)
#df.tail(3)

,Category,FullName,ShortName,ObjectAddress,geoData
0,Категория,Полное наименование,Сокращённое наименование,Адреса объекта,geoData
1,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 48 ДЗМ,AdmArea:Юго-Восточный административный округ\n...,"{coordinates=[[37.74188144, 55.694081483]], ty..."
2,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 110 филиал № 3 ДЗМ,AdmArea:Северо-Восточный административный окру...,"{coordinates=[[37.579720035, 55.814071213]], t..."

In [4]:
df.info()
#df.describe()
#df.columns
#df.shape

<class 'pandas.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Category       202 non-null    str
 1   FullName       202 non-null    str
 2   ShortName      202 non-null    str
 3   ObjectAddress  202 non-null    str
 4   geoData        202 non-null    str
dtypes: str(5)
memory usage: 8.0 KB

In [5]:
df['ShortName'].nunique()

202

In [6]:
df['ObjectAddress'].nunique()

201

In [9]:
df['ShortName'].unique()

<StringArray>
[                                             'Сокращённое наименование',
                                                     'ГБУЗ ДГП № 48 ДЗМ',
                                         'ГБУЗ ДГП № 110 филиал № 3 ДЗМ',
                                         'ГБУЗ ДГП № 131 филиал № 2 ДЗМ',
                                          'ГБУЗ ДГП № 91 филиал № 2 ДЗМ',
                                         'ГБУЗ ДГП № 150 филиал № 3 ДЗМ',
                                          'ГБУЗ ДГП № 61 филиал № 2 ДЗМ',
                                         'ГБУЗ ДГП № 122 филиал № 2 ДЗМ',
                                         'ГБУЗ ДГП № 125 филиал № 2 ДЗМ',
                                         'ГБУЗ ДГП № 150 филиал № 2 ДЗМ',
 ...
                                         'ГБУЗ ДГП № 104 филиал № 1 ДЗМ',
                                                     'ГБУЗ ДГП № 39 ДЗМ',
                                          'ГБУЗ ДГП № 30 филиал № 1 ДЗМ',
                                         'ГБУЗ ДГП № 104 филиал № 3 ДЗМ',
 'ГБУЗ Поликлиника г. Московский филиал № 2 ДЗМ. Кабинет врача педиатра',
                                                    'ГБУЗ ДГП № 130 ДЗМ',
                                 'ГБУЗ ДГП № 145 ДЗМ. Детское отделение',
                                                    'ГБУЗ ДГП № 105 ДЗМ',
                                          'ГБУЗ ДГП № 69 филиал № 2 ДЗМ',
                                         'ГБУЗ ДГП № 118 филиал № 7 ДЗМ']
Length: 202, dtype: str

In [36]:
df.loc[1,'geoData']

'{coordinates=[[37.682286593, 55.751888047]], type=MultiPoint}'

In [8]:
df["address"] = df["ObjectAddress"].str.extract(r"Address:(.*)")

In [11]:
df = df.drop(index=0).reset_index(drop=True)

In [12]:
df.head(10)

,Category,FullName,ShortName,ObjectAddress,geoData,address
0,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 48 ДЗМ,AdmArea:Юго-Восточный административный округ\n...,"{coordinates=[[37.74188144, 55.694081483]], ty...","Российская Федерация, город Москва, внутригоро..."
1,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 110 филиал № 3 ДЗМ,AdmArea:Северо-Восточный административный окру...,"{coordinates=[[37.579720035, 55.814071213]], t...","Российская Федерация, город Москва, внутригоро..."
2,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 131 филиал № 2 ДЗМ,AdmArea:Западный административный округ\nDistr...,"{coordinates=[[37.514133891, 55.712573334]], t...","Российская Федерация, город Москва, внутригоро..."
3,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 91 филиал № 2 ДЗМ,AdmArea:Южный административный округ\nDistrict...,"{coordinates=[[37.617093435, 55.714439742]], t...","Российская Федерация, город Москва, внутригоро..."
4,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 150 филиал № 3 ДЗМ,AdmArea:Юго-Восточный административный округ\n...,"{coordinates=[[37.74702014, 55.651710188]], ty...","Российская Федерация, город Москва, внутригоро..."
5,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 61 филиал № 2 ДЗМ,AdmArea:Юго-Восточный административный округ\n...,"{coordinates=[[37.66475943, 55.729622049]], ty...","Российская Федерация, город Москва, внутригоро..."
6,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 122 филиал № 2 ДЗМ,AdmArea:Восточный административный округ\nDist...,"{coordinates=[[37.802977987, 55.816576302]], t...","Российская Федерация, город Москва, внутригоро..."
7,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 125 филиал № 2 ДЗМ,AdmArea:Северо-Восточный административный окру...,"{coordinates=[[37.577723351, 55.901862208]], t...","Российская Федерация, город Москва, внутригоро..."
8,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 150 филиал № 2 ДЗМ,AdmArea:Юго-Восточный административный округ\n...,"{coordinates=[[37.769740489, 55.670141578]], t...","Российская Федерация, город Москва, внутригоро..."
9,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 48 филиал № 2 ДЗМ,AdmArea:Юго-Восточный административный округ\n...,"{coordinates=[[37.776995007, 55.701673799]], t...","Российская Федерация, город Москва, внутригоро..."

In [14]:
import re

def to_point_wkt(value):
    lon, lat = re.findall(r"[-\d.]+", value)[:2]
    return f"POINT({lon} {lat})"

df["location"] = df["geoData"].apply(to_point_wkt)

In [15]:
df.head(10)

,Category,FullName,ShortName,ObjectAddress,geoData,address,geometry,location
0,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 48 ДЗМ,AdmArea:Юго-Восточный административный округ\n...,"{coordinates=[[37.74188144, 55.694081483]], ty...","Российская Федерация, город Москва, внутригоро...",POINT(37.74188144 55.694081483),POINT(37.74188144 55.694081483)
1,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 110 филиал № 3 ДЗМ,AdmArea:Северо-Восточный административный окру...,"{coordinates=[[37.579720035, 55.814071213]], t...","Российская Федерация, город Москва, внутригоро...",POINT(37.579720035 55.814071213),POINT(37.579720035 55.814071213)
2,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 131 филиал № 2 ДЗМ,AdmArea:Западный административный округ\nDistr...,"{coordinates=[[37.514133891, 55.712573334]], t...","Российская Федерация, город Москва, внутригоро...",POINT(37.514133891 55.712573334),POINT(37.514133891 55.712573334)
3,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 91 филиал № 2 ДЗМ,AdmArea:Южный административный округ\nDistrict...,"{coordinates=[[37.617093435, 55.714439742]], t...","Российская Федерация, город Москва, внутригоро...",POINT(37.617093435 55.714439742),POINT(37.617093435 55.714439742)
4,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 150 филиал № 3 ДЗМ,AdmArea:Юго-Восточный административный округ\n...,"{coordinates=[[37.74702014, 55.651710188]], ty...","Российская Федерация, город Москва, внутригоро...",POINT(37.74702014 55.651710188),POINT(37.74702014 55.651710188)
5,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 61 филиал № 2 ДЗМ,AdmArea:Юго-Восточный административный округ\n...,"{coordinates=[[37.66475943, 55.729622049]], ty...","Российская Федерация, город Москва, внутригоро...",POINT(37.66475943 55.729622049),POINT(37.66475943 55.729622049)
6,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 122 филиал № 2 ДЗМ,AdmArea:Восточный административный округ\nDist...,"{coordinates=[[37.802977987, 55.816576302]], t...","Российская Федерация, город Москва, внутригоро...",POINT(37.802977987 55.816576302),POINT(37.802977987 55.816576302)
7,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 125 филиал № 2 ДЗМ,AdmArea:Северо-Восточный административный окру...,"{coordinates=[[37.577723351, 55.901862208]], t...","Российская Федерация, город Москва, внутригоро...",POINT(37.577723351 55.901862208),POINT(37.577723351 55.901862208)
8,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 150 филиал № 2 ДЗМ,AdmArea:Юго-Восточный административный округ\n...,"{coordinates=[[37.769740489, 55.670141578]], t...","Российская Федерация, город Москва, внутригоро...",POINT(37.769740489 55.670141578),POINT(37.769740489 55.670141578)
9,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 48 филиал № 2 ДЗМ,AdmArea:Юго-Восточный административный округ\n...,"{coordinates=[[37.776995007, 55.701673799]], t...","Российская Федерация, город Москва, внутригоро...",POINT(37.776995007 55.701673799),POINT(37.776995007 55.701673799)

In [16]:
df.drop(columns=["ObjectAddress"], inplace=True)
df.drop(columns=["geoData"], inplace=True)
df.drop(columns=["geometry"], inplace=True)
df.head(10)

,Category,FullName,ShortName,address,location
0,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 48 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.74188144 55.694081483)
1,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 110 филиал № 3 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.579720035 55.814071213)
2,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 131 филиал № 2 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.514133891 55.712573334)
3,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 91 филиал № 2 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.617093435 55.714439742)
4,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 150 филиал № 3 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.74702014 55.651710188)
5,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 61 филиал № 2 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.66475943 55.729622049)
6,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 122 филиал № 2 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.802977987 55.816576302)
7,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 125 филиал № 2 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.577723351 55.901862208)
8,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 150 филиал № 2 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.769740489 55.670141578)
9,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 48 филиал № 2 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.776995007 55.701673799)

In [17]:
df_unique = df.drop_duplicates(subset=["ShortName"], keep="first")

In [18]:
# df_unique.info()
# df_unique.describe()
df['ShortName'].value_counts()
# df_unique['address'].value_counts().head(10)

ShortName
ГБУЗ ДГП № 48 ДЗМ                        1
ГБУЗ ДГП № 110 филиал № 3 ДЗМ            1
ГБУЗ ДГП № 131 филиал № 2 ДЗМ            1
ГБУЗ ДГП № 91 филиал № 2 ДЗМ             1
ГБУЗ ДГП № 150 филиал № 3 ДЗМ            1
                                        ..
ГБУЗ ДГП № 130 ДЗМ                       1
ГБУЗ ДГП № 145 ДЗМ. Детское отделение    1
ГБУЗ ДГП № 105 ДЗМ                       1
ГБУЗ ДГП № 69 филиал № 2 ДЗМ             1
ГБУЗ ДГП № 118 филиал № 7 ДЗМ            1
Name: count, Length: 201, dtype: int64

In [19]:
df_unique = df[df["ShortName"].str.len() > 0]

In [20]:
df_unique = df_unique[df_unique["ShortName"].notna()]
df_unique.info()

<class 'pandas.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Category   201 non-null    str
 1   FullName   201 non-null    str
 2   ShortName  201 non-null    str
 3   address    201 non-null    str
 4   location   201 non-null    str
dtypes: str(5)
memory usage: 8.0 KB

In [21]:
df_unique = df_unique[~df_unique["ShortName"].str.contains("none", case=False, na=False)]
df_unique.info()

<class 'pandas.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Category   201 non-null    str
 1   FullName   201 non-null    str
 2   ShortName  201 non-null    str
 3   address    201 non-null    str
 4   location   201 non-null    str
dtypes: str(5)
memory usage: 8.0 KB

In [22]:
df_unique['address'].value_counts()

address
Российская Федерация, город Москва, внутригородская территория муниципальный округ Рязанский, Волжский бульвар, дом 9                          2
Российская Федерация, город Москва, внутригородская территория муниципальный округ Текстильщики, улица Артюхиной, дом 27, корпус 3             1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Бутырский, улица Яблочкова, дом 3А, строение 1              1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Раменки, Мосфильмовская улица, дом 27А                      1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Даниловский, улица Лестева, дом 5                           1
                                                                                                                                              ..
Российская Федерация, город Москва, внутригородская территория муниципальный округ Крылатское, улица Крылатские Холмы, дом 5                   1
город Москва, Каширское шоссе, дом 57, корпус 1                                                                                                1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Старое Крюково, город Зеленоград, корпус 805, строение 1    1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Зюзино, Азовская улица, дом 20, корпус 2                    1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Южное Бутово, 2-я Мелитопольская улица, дом 13              1
Name: count, Length: 200, dtype: int64

In [23]:
last = df["address"].str.split(",").str[-1].str.strip()
has_number = last.str.contains(r"\d", na=False, regex=True)

df_unique = df_unique[has_number]  # оставить только строки, где в «хвосте» адреса есть цифра
df_unique.info()

<class 'pandas.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Category   201 non-null    str
 1   FullName   201 non-null    str
 2   ShortName  201 non-null    str
 3   address    201 non-null    str
 4   location   201 non-null    str
dtypes: str(5)
memory usage: 8.0 KB

In [24]:
df_unique['address'].value_counts()

address
Российская Федерация, город Москва, внутригородская территория муниципальный округ Рязанский, Волжский бульвар, дом 9                          2
Российская Федерация, город Москва, внутригородская территория муниципальный округ Текстильщики, улица Артюхиной, дом 27, корпус 3             1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Бутырский, улица Яблочкова, дом 3А, строение 1              1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Раменки, Мосфильмовская улица, дом 27А                      1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Даниловский, улица Лестева, дом 5                           1
                                                                                                                                              ..
Российская Федерация, город Москва, внутригородская территория муниципальный округ Крылатское, улица Крылатские Холмы, дом 5                   1
город Москва, Каширское шоссе, дом 57, корпус 1                                                                                                1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Старое Крюково, город Зеленоград, корпус 805, строение 1    1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Зюзино, Азовская улица, дом 20, корпус 2                    1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Южное Бутово, 2-я Мелитопольская улица, дом 13              1
Name: count, Length: 200, dtype: int64

In [51]:
df_unique["address"] = df_unique["address"].str.replace(
    r"(\d+)\s*([кКkK])\s*(\d+)",
    r"\1 корпус \3",
    regex=True,
)

In [52]:
df_unique['address'].value_counts()

address
Российская Федерация, город Москва, внутригородская территория муниципальный округ Краснопахорский, посёлок Шишкин Лес, дом 32, строение 1                  2
Российская Федерация, город Москва, внутригородская территория муниципальный округ Коммунарка, посёлок Коммунарка, Фитарёвская улица, дом 27, строение 1    2
город Москва, Пехотная улица, дом 3, строение 16                                                                                                            2
Российская Федерация, город Москва, внутригородская территория муниципальный округ Богородское, Игральная улица, дом 8                                      2
Российская Федерация, город Москва, внутригородская территория муниципальный округ Москворечье-Сабурово, улица Кошкина, дом 21                              2
                                                                                                                                                           ..
Российская Федерация, город Москва, внутригородская территория муниципальный округ Западное Дегунино, Ангарская улица, дом 24                               1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Западное Дегунино, улица Маршала Федоренко, дом 6, строение 1            1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Ховрино, Петрозаводская улица, дом 26                                    1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Куркино, Родионовская улица, дом 10, корпус 2                            1
Российская Федерация, город Москва, внутригородская территория муниципальный округ Левобережный, Смольная улица, дом 53                                     1
Name: count, Length: 257, dtype: int64

In [28]:
df_unique.head(1)

,Category,FullName,ShortName,address,location
0,Поликлиника детская,Государственное бюджетное учреждение здравоохр...,ГБУЗ ДГП № 48 ДЗМ,"Российская Федерация, город Москва, внутригоро...",POINT(37.74188144 55.694081483)

In [29]:
df_unique = df_unique.rename(columns={
    "Category": "category",
    "FullName": "fullname",
    "ShortName": "shortname",
    "Address": "address",
})

In [30]:
df_unique.to_csv("policlinics_2.csv", index=False, encoding="utf-8")