In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("kndgds_f1.csv")
df.head(2)

,fullname,shortname,number,category,vid_uchrezhdeniya,organiz_pravov_forma,podchinenie,address,Latitude,Longitude,telephone,email
0,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1439,1 439,Дошкольное образовательное учреждение,Детский сад компенсирующего вида,Бюджетное,Северо-Восточное окружное управление образования,"""127273 г. Москва, ул. Отрадная, д. 5 ""Б""",55.859119,37.607619,(499) 907-63-66,detsad1439@mail.ru
1,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 938,938,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Северо-Восточное окружное управление образования,"127349, город Москва, улица Лескова, дом 6 Г",55.897075,37.592568,(499) 909-00-44,detskiysad938@yandex.ru

In [3]:
df['Latitude'] = pd.to_numeric(df['Latitude'], errors='coerce')
df['Longitude'] = pd.to_numeric(df['Longitude'], errors='coerce')
df['location'] = df.apply(
    lambda row: f"POINT({row['Longitude']} {row['Latitude']})"
    if pd.notna(row['Longitude']) and pd.notna(row['Latitude'])
    else None,
    axis=1
)
df.head()

,fullname,shortname,number,category,vid_uchrezhdeniya,organiz_pravov_forma,podchinenie,address,Latitude,Longitude,telephone,email,location
0,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1439,1 439,Дошкольное образовательное учреждение,Детский сад компенсирующего вида,Бюджетное,Северо-Восточное окружное управление образования,"""127273 г. Москва, ул. Отрадная, д. 5 ""Б""",55.859119,37.607619,(499) 907-63-66,detsad1439@mail.ru,POINT(37.6076187 55.8591187)
1,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 938,938,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Северо-Восточное окружное управление образования,"127349, город Москва, улица Лескова, дом 6 Г",55.897075,37.592568,(499) 909-00-44,detskiysad938@yandex.ru,POINT(37.5925685 55.8970746)
2,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1243,1 243,Дошкольное образовательное учреждение,Детский сад компенсирующего вида,Бюджетное,Юго-Западное окружное управление образования,"119333, г. Москва, ул. Фотиевой, дом 8",55.701004,37.562349,8(499)137-35-75,dou1243@ou.mosuzedu.ru; tngulakova@bk.ru,POINT(37.5623493 55.70100369999999)
3,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1432,1 432,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Юго-Западное окружное управление образования,"119331, г.Москва, улица Марии Ульяновой, дом ...",55.680765,37.520382,8(499)138-38-47,dou1432@ou.mosuzedu.ru,POINT(37.5203819 55.680765)
4,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 824,824,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Западное окружное управление образования,"121615, г.Москва, ул. Ельнинская, д. 16",55.738647,37.424016,(499) 141-75-87,dou824@bk.ru,POINT(37.4240156 55.7386473)

In [4]:
# Удаление лишних столбцов
df = df.drop(columns=['Latitude', 'Longitude'])
df.head(3)
#df.tail(3)

,fullname,shortname,number,category,vid_uchrezhdeniya,organiz_pravov_forma,podchinenie,address,telephone,email,location
0,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1439,1 439,Дошкольное образовательное учреждение,Детский сад компенсирующего вида,Бюджетное,Северо-Восточное окружное управление образования,"""127273 г. Москва, ул. Отрадная, д. 5 ""Б""",(499) 907-63-66,detsad1439@mail.ru,POINT(37.6076187 55.8591187)
1,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 938,938,Дошкольное образовательное учреждение,Детский сад,Бюджетное,Северо-Восточное окружное управление образования,"127349, город Москва, улица Лескова, дом 6 Г",(499) 909-00-44,detskiysad938@yandex.ru,POINT(37.5925685 55.8970746)
2,Государственное бюджетное образовательное учр...,ГБОУ детский сад № 1243,1 243,Дошкольное образовательное учреждение,Детский сад компенсирующего вида,Бюджетное,Юго-Западное окружное управление образования,"119333, г. Москва, ул. Фотиевой, дом 8",8(499)137-35-75,dou1243@ou.mosuzedu.ru; tngulakova@bk.ru,POINT(37.5623493 55.70100369999999)

In [5]:
df.info()
#df.describe()
#df.columns
#df.shape

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fullname              1000 non-null   str
 1   shortname             1000 non-null   str
 2   number                1000 non-null   str
 3   category              1000 non-null   str
 4   vid_uchrezhdeniya     1000 non-null   str
 5   organiz_pravov_forma  1000 non-null   str
 6   podchinenie           1000 non-null   str
 7   address               1000 non-null   str
 8   telephone             1000 non-null   str
 9   email                 1000 non-null   str
 10  location              1000 non-null   str
dtypes: str(11)
memory usage: 86.1 KB

In [6]:
df.to_csv("kndrgdens_1.csv", index=False, encoding="utf-8")