In [1]:
import pandas as pd
df = pd.read_csv("obschepit_csv_filtered.csv")
df.head()

,id,Code,Name,global_id,Is net object,Operating company,Object type,Area,District,Address,Public phone,Seats amount,Presence of privileges,Longitude in WGS-84,Latitude in WGS-84,Geodata,Centroid
0,1,77874,Родник,637376331,нет,NaN,кафе,Центральный административный округ,Таганский район,"город Москва, улица Талалихина, дом 2/1, корпус 1",PublicPhone:(495) 676-55-35,35,нет,37.673306,55.738239,"type:Point\ncoordinates:37.67330613,55.738238655","{type=Point, coordinates=[37.67330613, 55.7382..."
1,2,24309,Кафе «Академия»,637376349,нет,NaN,ресторан,Центральный административный округ,Таганский район,"Российская Федерация, город Москва, внутригоро...",PublicPhone:(495) 662-30-10,95,нет,37.669648,55.735511,"type:Point\ncoordinates:37.669647597,55.735511472","{type=Point, coordinates=[37.669647597, 55.735..."
2,4,148815,Брусника,637376481,да,Брусника,кафе,Центральный административный округ,район Арбат,"Российская Федерация, город Москва, внутригоро...",PublicPhone:(495) 697-04-89,10,нет,37.598089,55.747449,"type:Point\ncoordinates:37.598089,55.747448755","{type=Point, coordinates=[37.598089, 55.747448..."
3,5,23394,Хинкальная Гогиели,637376678,нет,NaN,кафе,Юго-Восточный административный округ,район Лефортово,"Российская Федерация, город Москва, внутригоро...",PublicPhone:(495) 361-38-50,24,нет,37.719950,55.749276,"type:Point\ncoordinates:37.719950379,55.749275989","{type=Point, coordinates=[37.719950379, 55.749..."
4,6,22579,Алло Пицца,637376719,да,Алло Пицца,кафе,Западный административный округ,район Солнцево,"Российская Федерация, город Москва, внутригоро...",PublicPhone:(495) 934-31-00,32,нет,37.398531,55.645103,"type:Point\ncoordinates:37.398531,55.645102725","{type=Point, coordinates=[37.398531, 55.645102..."

In [2]:
df["location"] = (
    "POINT("
    + df["Longitude in WGS-84"].map("{:.6f}".format)
    + " "
    + df["Latitude in WGS-84"].map("{:.6f}".format)
    + ")"
).astype("string")

In [3]:
df["location"].dtype

In [4]:
df.head()

,id,Code,Name,global_id,Is net object,Operating company,Object type,Area,District,Address,Public phone,Seats amount,Presence of privileges,Longitude in WGS-84,Latitude in WGS-84,Geodata,Centroid,location
0,1,77874,Родник,637376331,нет,NaN,кафе,Центральный административный округ,Таганский район,"город Москва, улица Талалихина, дом 2/1, корпус 1",PublicPhone:(495) 676-55-35,35,нет,37.673306,55.738239,"type:Point\ncoordinates:37.67330613,55.738238655","{type=Point, coordinates=[37.67330613, 55.7382...",POINT(37.6733061300344 55.7382386551547)
1,2,24309,Кафе «Академия»,637376349,нет,NaN,ресторан,Центральный административный округ,Таганский район,"Российская Федерация, город Москва, внутригоро...",PublicPhone:(495) 662-30-10,95,нет,37.669648,55.735511,"type:Point\ncoordinates:37.669647597,55.735511472","{type=Point, coordinates=[37.669647597, 55.735...",POINT(37.6696475969381 55.7355114718314)
2,4,148815,Брусника,637376481,да,Брусника,кафе,Центральный административный округ,район Арбат,"Российская Федерация, город Москва, внутригоро...",PublicPhone:(495) 697-04-89,10,нет,37.598089,55.747449,"type:Point\ncoordinates:37.598089,55.747448755","{type=Point, coordinates=[37.598089, 55.747448...",POINT(37.598089 55.747448754930645)
3,5,23394,Хинкальная Гогиели,637376678,нет,NaN,кафе,Юго-Восточный административный округ,район Лефортово,"Российская Федерация, город Москва, внутригоро...",PublicPhone:(495) 361-38-50,24,нет,37.719950,55.749276,"type:Point\ncoordinates:37.719950379,55.749275989","{type=Point, coordinates=[37.719950379, 55.749...",POINT(37.71995037885907 55.74927598927656)
4,6,22579,Алло Пицца,637376719,да,Алло Пицца,кафе,Западный административный округ,район Солнцево,"Российская Федерация, город Москва, внутригоро...",PublicPhone:(495) 934-31-00,32,нет,37.398531,55.645103,"type:Point\ncoordinates:37.398531,55.645102725","{type=Point, coordinates=[37.398531, 55.645102...",POINT(37.398531000000006 55.6451027253736)

In [6]:
df['Object type'].value_counts()

Object type
кафе                       8321
ресторан                   2728
бар                        1516
ночной клуб (дискотека)      84
Name: count, dtype: int64

In [7]:
df.to_csv("obschepit_filt.csv", index=False)