In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('etagi_flats.csv')
df.head(3)
df.tail(3)

,ticket_id,price,square,rooms,studio,floor,floors_total,building_year,metro,metro_dist,time_to_metro,address,keep,photo,url
44757,NaN,92858544,121.9,3,False,20,21.0,NaN,метро Терехово,200.0,3.0,"Москва, Хорошёво-Мнёвники, None 2",Не указано,NaN,NaN
44758,NaN,25804620,34.5,0,True,12,14.0,NaN,метро Мнёвники,100.0,2.0,"Москва, Хорошёво-Мнёвники, Нижние Мнёвники 62бк2",Не указано,NaN,NaN
44759,NaN,21668358,54.2,2,False,30,30.0,NaN,метро Аннино,400.0,6.0,"Москва, Чертаново Южное, None",Не указано,NaN,NaN

In [8]:
df.info()
#df.describe()
#df.columns
#df.shape

<class 'pandas.DataFrame'>
RangeIndex: 44760 entries, 0 to 44759
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ticket_id      3741 non-null   float64
 1   price          44760 non-null  int64
 2   square         44760 non-null  float64
 3   rooms          44760 non-null  int64
 4   studio         44760 non-null  bool
 5   floor          44760 non-null  int64
 6   floors_total   44673 non-null  float64
 7   building_year  13769 non-null  float64
 8   metro          39005 non-null  str
 9   metro_dist     39005 non-null  float64
 10  time_to_metro  39005 non-null  float64
 11  address        44760 non-null  str
 12  keep           44760 non-null  str
 13  photo          43397 non-null  str
 14  url            3742 non-null   str
dtypes: bool(1), float64(6), int64(3), str(5)
memory usage: 4.8 MB

In [10]:
df['address'].nunique()

3219

In [32]:
df_n_b = df[df['building_year'] >= 2025]

In [34]:
df_n_b.head(2)

,ticket_id,price,square,rooms,studio,floor,floors_total,building_year,metro,metro_dist,time_to_metro,address,keep,photo,url
37,12146164.0,28970000,47.0,1,False,5,8.0,2027.0,метро Добрынинская,1500.0,23.0,"Москва, Даниловский, Дубининская 59к2",Не указано,https://cdn.esoft.digital/content/cluster/ecoo...,https://msk.etagi.com/realty/12146164/
62,12137437.0,20000000,40.0,1,False,4,22.0,2025.0,метро Народное Ополчение,600.0,9.0,"Москва, Хорошёво-Мнёвники, Демьяна Бедного 22а",Не указано,https://cdn.esoft.digital/content/cluster/ecoo...,https://msk.etagi.com/realty/12137437/

In [35]:
df_n_b['address'].nunique()

282

In [36]:
df_n_b['building_year'].unique()

array([2027., 2025., 2026., 2028.])

In [31]:
# df_new_buildings.info()

In [37]:
df_unique = df_n_b.drop_duplicates(subset=["address"], keep="first")

In [39]:
# df_unique.info()
# df_unique.describe()
df_unique['address'].value_counts()
# df_unique['address'].value_counts().head(10)

address
Москва, Даниловский, Дубининская 59к2             1
Москва, Хорошёво-Мнёвники, Демьяна Бедного 22а    1
Москва, Очаково-Матвеевское, Озёрная 1к1          1
Москва, Басманный, Малая Почтовая 12              1
Москва, Нижегородский, None 3                     1
                                                 ..
Сосенское, None к9.1                              1
Московский, None 68.4                             1
Филимонковское, None 4                            1
Внуковское, Анны Ахматовой 11к6                   1
Москва, Савёловский, None                         1
Name: count, Length: 282, dtype: int64

In [40]:
df_unique = df_unique[df_unique["address"].str.len() > 0]

In [42]:
df_unique = df_unique[df_unique["address"].notna()]
df_unique.info()

<class 'pandas.DataFrame'>
Index: 282 entries, 37 to 43458
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ticket_id      140 non-null    float64
 1   price          282 non-null    int64
 2   square         282 non-null    float64
 3   rooms          282 non-null    int64
 4   studio         282 non-null    bool
 5   floor          282 non-null    int64
 6   floors_total   282 non-null    float64
 7   building_year  282 non-null    float64
 8   metro          222 non-null    str
 9   metro_dist     222 non-null    float64
 10  time_to_metro  222 non-null    float64
 11  address        282 non-null    str
 12  keep           282 non-null    str
 13  photo          278 non-null    str
 14  url            140 non-null    str
dtypes: bool(1), float64(6), int64(3), str(5)
memory usage: 33.3 KB

In [44]:
df_unique = df_unique[~df_unique["address"].str.contains("none", case=False, na=False)]
df_unique.info()

<class 'pandas.DataFrame'>
Index: 111 entries, 37 to 42916
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ticket_id      69 non-null     float64
 1   price          111 non-null    int64
 2   square         111 non-null    float64
 3   rooms          111 non-null    int64
 4   studio         111 non-null    bool
 5   floor          111 non-null    int64
 6   floors_total   111 non-null    float64
 7   building_year  111 non-null    float64
 8   metro          103 non-null    str
 9   metro_dist     103 non-null    float64
 10  time_to_metro  103 non-null    float64
 11  address        111 non-null    str
 12  keep           111 non-null    str
 13  photo          108 non-null    str
 14  url            69 non-null     str
dtypes: bool(1), float64(6), int64(3), str(5)
memory usage: 13.1 KB

In [45]:
df_unique['address'].value_counts()

address
Москва, Даниловский, Дубининская 59к2             1
Москва, Хорошёво-Мнёвники, Демьяна Бедного 22а    1
Москва, Очаково-Матвеевское, Озёрная 1к1          1
Москва, Басманный, Малая Почтовая 12              1
Москва, Алтуфьевский, Алтуфьевское шоссе 55к4     1
                                                 ..
Сосенское, проспект Куприна 11к2                  1
Сосенское, проспект Куприна 11к1                  1
Сосенское, проспект Куприна 9к1                   1
Сосенское, Братьев Гранат                         1
Внуковское, Анны Ахматовой 11к6                   1
Name: count, Length: 111, dtype: int64

In [46]:
last = df["address"].str.split(",").str[-1].str.strip()
has_number = last.str.contains(r"\d", na=False, regex=True)

df_unique = df_unique[has_number]  # оставить только строки, где в «хвосте» адреса есть цифра
df_unique.info()

<class 'pandas.DataFrame'>
Index: 102 entries, 37 to 42916
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ticket_id      66 non-null     float64
 1   price          102 non-null    int64
 2   square         102 non-null    float64
 3   rooms          102 non-null    int64
 4   studio         102 non-null    bool
 5   floor          102 non-null    int64
 6   floors_total   102 non-null    float64
 7   building_year  102 non-null    float64
 8   metro          95 non-null     str
 9   metro_dist     95 non-null     float64
 10  time_to_metro  95 non-null     float64
 11  address        102 non-null    str
 12  keep           102 non-null    str
 13  photo          99 non-null     str
 14  url            66 non-null     str
dtypes: bool(1), float64(6), int64(3), str(5)
memory usage: 12.1 KB

/var/folders/nr/dkzrdrrx1kzb8nlxz2jwwjb00000gq/T/ipykernel_24462/839650233.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_unique = df_unique[has_number]  # оставить только строки, где в «хвосте» адреса есть цифра

In [47]:
df_unique['address'].value_counts()

address
Москва, Даниловский, Дубининская 59к2             1
Москва, Хорошёво-Мнёвники, Демьяна Бедного 22а    1
Москва, Очаково-Матвеевское, Озёрная 1к1          1
Москва, Басманный, Малая Почтовая 12              1
Москва, Алтуфьевский, Алтуфьевское шоссе 55к4     1
                                                 ..
Москва, Западное Дегунино, Ильменский проезд 2    1
Сосенское, проспект Куприна 11к2                  1
Сосенское, проспект Куприна 11к1                  1
Сосенское, проспект Куприна 9к1                   1
Внуковское, Анны Ахматовой 11к6                   1
Name: count, Length: 102, dtype: int64

In [51]:
df_unique["address"] = df_unique["address"].str.replace(
    r"(\d+)\s*([кКkK])\s*(\d+)",
    r"\1 корпус \3",
    regex=True,
)

In [52]:
df_unique['address'].value_counts()

address
Москва, Даниловский, Дубининская 59 корпус 2            1
Москва, Хорошёво-Мнёвники, Демьяна Бедного 22а          1
Москва, Очаково-Матвеевское, Озёрная 1 корпус 1         1
Москва, Басманный, Малая Почтовая 12                    1
Москва, Алтуфьевский, Алтуфьевское шоссе 55 корпус 4    1
                                                       ..
Москва, Западное Дегунино, Ильменский проезд 2          1
Сосенское, проспект Куприна 11 корпус 2                 1
Сосенское, проспект Куприна 11 корпус 1                 1
Сосенское, проспект Куприна 9 корпус 1                  1
Внуковское, Анны Ахматовой 11 корпус 6                  1
Name: count, Length: 102, dtype: int64

In [55]:
df_unique.to_csv("new_buildings.csv", index=False, encoding="utf-8")